# Generated by Django 4.2.5 on 2023-12-16 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('users', models.ManyToManyField(null=True, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
