# Generated by Django 4.2.5 on 2023-12-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Waiting', max_length=11),
        ),
    ]
